### ISSUE TITLE
it's refreshing while scrolling

### ISSUE THREAD

**Issue by ismaiI1** [coderyi/YiRefresh#1]
my tableviewcell count is 436. when i scroll the tableview, YiRefresh is working and refreshing the table. I checked your sample app. Result is same. how can i fix this?

**Comment by coderyi** [comment]
can you give me a screen shot for this problem？you can send a email to me，coderyi@foxmail.com

**Comment by ismaiI1** [comment]
i give up to use this library. i am using https://github.com/shiki/STableViewController . it's stable. thank you .

**Comment by coderyi** [comment]
I am very happy you to give that issue，and I have solved this issue.detail url is  http://dwz.cn/EOsd9  ，thank you！

**Comment by ismaiI1** [comment]
I'm glad you solved this issue. i'll use this library next time :)
