### ISSUE TITLE
上拉加载更多位移没有置零导致有空白条

### ISSUE THREAD

**Issue by KamingInWork** [coderyi/YiRefresh#3]
[UIView animateWithDuration:0.3 animations:^{
            [activityView stopAnimating];

//            _scrollView.contentInset=UIEdgeInsetsMake(0, 0, footerHeight, 0);
// 改成这样
            _scrollView.contentInset = UIEdgeInsetsMake(0, 0, 0, 0);
            footerView.frame=CGRectMake(0, contentHeight, IPHONE_WIDTH, footerHeight);
        }];

**Comment by coderyi** [comment]
thank you

**Comment by KamingInWork** [comment]
还有个问题，就是当当前界面不满足contentsize.height > scroller.frame.size.height时候，不会有上拉刷新。同时，如果push进入超过3个界面，同时有代码对 didscroll进行操作，会超级卡，估计是kvo的锅

**Comment by ispiropoulos** [comment]
The correct way is:
 scrollWidth = [[UIScreen mainScreen] bounds].size.width;

this way the refresh control appears always in the middle (iOS 9 tested)
