### ISSUE TITLE
I can't change refresh title.

### ISSUE THREAD

**Issue by Ying1986** [coderyi/YiRefresh#5]
Current library is impossible to change pulling title.

Can you added interface to change title?

@coderyi

**Comment by coderyi** [comment]
thank you,now you can change it in "YiRefreshHeader.h"

<pre>
#define kRefreshHeaderTitleLoading @"正在载入…"
#define kRefreshHeaderTitlePullDown @"下拉可刷新"
#define kRefreshHeaderTitleRelease @"松开以刷新"
</pre>

**Comment by Ying1986** [comment]
@coderyi 
Thank you.

I want to change title by function or change method. (english)
I'm using your code as pod project, so I can't change macro.
Can you add property or method?

e.g.: setTitleLoading:(NSString*) title

Regards

**Comment by coderyi** [comment]
your advice will be ok，but it cann't change YiRefresh's title,only a YiRefreshHeader Object。

and I add three property that you can use,

<pre>
@property(nonatomic,copy) NSString *titleLoading;// YiRefresh header loading title
@property(nonatomic,copy) NSString *titlePullDown;//YiRefresh header pull down title
@property(nonatomic,copy) NSString *titleRelease;//YiRefresh header release title
</pre>

**Comment by Ying1986** [comment]
@coderyi 

Great thank you.
